### ISSUE TITLE
Use CSS media queries to change multicolumn layout for one column layout

### ISSUE THREAD

**Issue by biernacki** [AlanLes/ZADANIE_NEW#1]
For product and category view use media queries to change from 2 columns to one column on window max-width 480px.

If you are using less preprocessor take a look here - http://lesscss.org/features/#features-overview-feature-nested-directives-and-bubbling

There you'll find an example how to add media queries break-points to your CSS rules.

**Comment by AlanLes** [comment]
already done, thanks :)
