### ISSUE TITLE
Use HTML5 elements everywhere possible

### ISSUE THREAD

**Issue by biernacki** [AlanLes/ZADANIE_NEW#2]
Use elements like 

```
<header/>
<footer/>
<section/>
<nav/>
<article/>
<aside/>
```
in your html documents whereever they are appropriate.

**Comment by escaton18** [comment]
The elements you wanted to list are not there, at least for me.
Post looks like that 
"Use elements like

, , , , , in your html documents whereever they are appropriate."

**Comment by biernacki** [comment]
Sorry, my mistake :) comment is updated

**Comment by AlanLes** [comment]
it's probably done. :+1:
